### ISSUE TITLE
本地如何调试

### ISSUE THREAD

**Issue by minms** [matchvs/Doc#8]
本地搭建完matchvs后, 如何在局域网内进行调试? 文档确实没找到!

**Comment by mushroom-1207** [comment]
本地搭建matchvs是指搭建gameServer吗？
可以参考http://www.matchvs.com/service?page=DemoJSgameServer
如果未解决你的问题，麻烦请提供更详细的信息
或者加入QQ群 450335262 ，直接向技术支持提问哦~
